language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction

notifications:
  slack:
    rooms:
      secure: XSMER5zUTZF07HpuV1ww7GH4FdesY5ZQ9WysjVR4EZ6jFKqdSDrZPrt2Ll9tDapMj9DkmMiAg1Siune8Kud1eQWoxz5K2Wucv4eWEDRfk9mqqex4vEofmdOMQW/rtZxX4lR6l8yrTSOxbHtMm4+hPdwDXHhAqpAA2kLhjPi71rgjzau8G7AIvnhgmGvdDQrj/f0XBXmiiieh9jn9Kp5B2zSHfwuaGO9wpvPyXRtDxmqB6W3sf1joRNeX56N6JAlYOrCReza7qXhY+QZVk3sEp7ohb3EBPcWeM82kRUHxUqzQr+teWxb3Gi38ZGTr8BmzFxDUTb18mPgr5TR97wd4OUv5uubC96J5mPVeSpOevhpa2JQzH5voeqCc9r7ujI8mu5ta76QDU50tXGBHkN3e/e+QMd3Smngqwj8CapJXslKQUGtBBc4yswTsncGjlDTtD1mhY/J3XJKl7g86kFqVCAg3HtHO17uzuL4KSVV0pfG057zvC+OZwLWDPTGSPbnSUGeBDo3KsDa9iML6pGQtARwPIhmwlk0qkNtguUb0bG8i8FDbqhky2+lli9o49B1tm2D03IpE6X/EHm/2gMuwQwprLzJHVckvueYRGu1218vawxwgXxvSSXCjflSqfwicgF/Btp0r1WI18VbnvIX8KU3NdVZcXBQFdGEoUSlo6wU=
